//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIM.Database.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertencia
    {
        public int Identificador { get; set; }
        public decimal Valor { get; set; }
        public string Pago { get; set; }
        public int IdOcorrencia { get; set; }
    
        public virtual Ocorrencia Ocorrencia { get; set; }
    }
}
