//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIM.Database.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ocorrencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ocorrencia()
        {
            this.Advertencias = new HashSet<Advertencia>();
        }
    
        public int Identificador { get; set; }
        public string Motivo { get; set; }
        public string Descricao { get; set; }
        public System.DateTime DataOcorrencia { get; set; }
        public int IdMorador { get; set; }
    
        public virtual Morador Morador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Advertencia> Advertencias { get; set; }
    }
}
