//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIM.Database.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int Identificador { get; set; }
        public System.DateTime DataReserva { get; set; }
        public int IdTipoReserva { get; set; }
        public string ConfirmacaoReserva { get; set; }
        public int IdMorador { get; set; }
    
        public virtual Morador Moradores { get; set; }
        public virtual TipoReserva TipoReserva { get; set; }
    }
}
