//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIM.Database.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int Identificador { get; set; }
        public string Login { get; set; }
        public string Senha { get; set; }
        public int IdGrupo { get; set; }
        public int IdColaborador { get; set; }
    
        public virtual Colaborador Colaborador { get; set; }
        public virtual GrupoUsuario GrupoUsuario { get; set; }
    }
}
