//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIM.Database.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apartamento()
        {
            this.Estacionamentos = new HashSet<Estacionamento>();
        }
    
        public int Identificador { get; set; }
        public int Bloco { get; set; }
        public string Numero { get; set; }
        public int IdContrato { get; set; }
    
        public virtual Contrato Contrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estacionamento> Estacionamentos { get; set; }
    }
}
