//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIM.Database.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contrato()
        {
            this.Apartamentos = new HashSet<Apartamento>();
        }
    
        public int Identificador { get; set; }
        public System.DateTime DataContrato { get; set; }
        public string Descricao { get; set; }
        public int IdAluguel { get; set; }
        public int IdMorador { get; set; }
    
        public virtual Aluguel Alugueis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apartamento> Apartamentos { get; set; }
        public virtual Morador Moradores { get; set; }
    }
}
