CREATE DATABASE PIM
GO

USE PIM
GO

CREATE TABLE CG_MORADORES(
	MOR_ID			INT IDENTITY(1,1)		NOT NULL	PRIMARY KEY,
	MOR_NOME		VARCHAR(100)			NOT NULL,
	MOR_RG			VARCHAR(20)				NULL,
	MOR_CPF			VARCHAR(15)				NOT NULL,
	MOR_TELEFONE	VARCHAR(20)				NOT NULL,
	MOR_CELULAR		VARCHAR(20)				NULL
);

CREATE TABLE CG_OCORRENCIA(
	OCO_ID			INT	IDENTITY(1,1)		NOT NULL	PRIMARY KEY,
	OCO_MOTIVO		VARCHAR(100)			NOT NULL,
	OCO_DESCRICAO	VARCHAR(400)			NOT NULL,
	OCO_DATA		DATETIME				NOT NULL	DEFAULT GETDATE(),
	MOR_REC			INT						NOT NULL	FOREIGN KEY REFERENCES CG_MORADORES(MOR_ID)
);

CREATE TABLE CG_DEPENDENTE(
	DEP_ID			INT IDENTITY(1,1)		NOT NULL	PRIMARY KEY,
	DEP_NOME		VARCHAR(100)			NOT NULL,
	DEP_RG			VARCHAR(20)				NULL,
	DEP_CPF			VARCHAR(20)				NULL,
	DEP_TELEFONE	VARCHAR(20)				NULL,
	MOR_RESPONSAVEL	INT						NOT NULL	FOREIGN KEY REFERENCES CG_MORADORES(MOR_ID)
);

CREATE TABLE CG_ALUGUEL(
	ALU_ID			INT	IDENTITY(1,1)		NOT NULL	PRIMARY KEY,
	ALU_VALOR		DECIMAL(18,2)			NOT	NULL
);

CREATE TABLE CG_CONTRATO(
	CON_ID			INT	IDENTITY(1,1)		NOT NULL	PRIMARY KEY,
	CON_DATA		DATETIME				NOT NULL,
	CON_DESCRICAO	VARCHAR(1000)			NOT NULL,
	CON_ALUGUEL		INT						NOT NULL	FOREIGN KEY REFERENCES CG_ALUGUEL(ALU_ID),
	CON_MORADOR		INT						NOT NULL	FOREIGN KEY REFERENCES CG_MORADORES(MOR_ID)
);

CREATE TABLE CG_APARTAMENTO(
	APA_ID			INT	IDENTITY(1,1)		NOT NULL	PRIMARY KEY,
	APA_BLOCO		INT						NOT NULL,
	APA_NUMERO		VARCHAR(5)				NOT NULL,
	APA_CONTRATO	INT						NOT NULL	FOREIGN KEY REFERENCES CG_CONTRATO(CON_ID)
);

CREATE TABLE CG_ESTACIONAMENTO(
	EST_ID			INT IDENTITY(1,1)		NOT NULL	PRIMARY KEY,
	EST_VAGAS		INT						NOT NULL,
	EST_AP			INT						NOT NULL	FOREIGN KEY REFERENCES CG_APARTAMENTO(APA_ID)
);

CREATE TABLE CG_TIPO_RESERVA(
	TP_ID			INT	IDENTITY(1,1)		NOT NULL	PRIMARY KEY,
	TP_TIPO_RESERVA	VARCHAR(30)				NOT	NULL
);

CREATE TABLE CG_RESERVAS(
	RES_ID			INT	IDENTITY(1,1)		NOT NULL	PRIMARY KEY,
	RES_DATA		DATETIME				NOT NULL,
	RES_TIPO		INT						NOT NULL	FOREIGN KEY	REFERENCES CG_TIPO_RESERVA(TP_ID),
	RES_CONFIR		CHAR(1)					NOT	NULL	CHECK(RES_CONFIR IN('S', 'N')),
	RES_MOD			INT						NOT NULL	FOREIGN KEY REFERENCES CG_MORADORES(MOR_ID)
);

CREATE TABLE CORE_GRUPO_USUARIO(
	GRP_ID			INT	IDENTITY(1,1)		NOT NULL	PRIMARY KEY,
	GRP_NOME		VARCHAR(50)				NOT NULL
);

CREATE TABLE CORE_COLABORADOR(
	COL_ID			INT	IDENTITY(1,1)		NOT NULL	PRIMARY KEY,
	COL_NOME		VARCHAR(100)			NOT NULL,
	COL_RG			VARCHAR(20)				NULL,
	COL_CPF			VARCHAR(20)				NOT NULL,
	COL_FUNCAO		VARCHAR(30)				NOT NULL,
	COL_SAL			DECIMAL(18,2)			NULL,
	COL_CONTRATO	DATETIME				NULL
);

CREATE TABLE CORE_USUARIO(
	USU_ID			INT IDENTITY(1,1)		NOT NULL	PRIMARY KEY,
	USU_LOGIN		VARCHAR(20)				NOT NULL,
	USU_SENHA		VARCHAR(100)			NOT NULL,
	USU_GRP			INT						NOT NULL	FOREIGN KEY REFERENCES CORE_GRUPO_USUARIO(GRP_ID),
	USU_COLAB		INT						NOT NULL	FOREIGN KEY	REFERENCES CORE_COLABORADOR(COL_ID)
);