CREATE DATABASE PIM
GO

USE PIM
GO

CREATE TABLE CG_MORADORES(
	MOR_ID			INT IDENTITY(1,1)		NOT NULL	PRIMARY KEY,
	MOR_NOME		VARCHAR(100)			NOT NULL,
	MOR_RG			VARCHAR(20)				NULL,
	MOR_CPF			VARCHAR(15)				NOT NULL,
	MOR_TELEFONE	VARCHAR(20)				NOT NULL,
	MOR_CELULAR		VARCHAR(20)				NULL
)

