USE PIM
GO

--

ALTER TABLE CG_MORADORES 
	ADD MOR_DATA_NASC		DATETIME		NULL,
		MOR_EMAIL			VARCHAR(100)	NULL;

ALTER TABLE CG_DEPENDENTE
	ADD	DEP_GRAU_PAR		CHAR(1)			NOT NULL;

ALTER TABLE	CG_CONTRATO
	ADD	CON_VALOR			DECIMAL(18,2)	NOT NULL,
		CON_PARCELAS		INT				NOT NULL,
		CON_TIPO			CHAR(1)			NOT NULL DEFAULT 'A';

ALTER TABLE CG_CONTRATO	DROP COLUMN CON_ALUGUEL;

DROP TABLE CG_ALUGUEL;

CREATE TABLE CG_ADVERTENCIA(
	ADV_ID			INT IDENTITY(1,1)		NOT NULL PRIMARY KEY,
	ADV_VALOR		DECIMAL(18,2)			NOT NULL,
	ADV_PAGO		CHAR(1)					NULL,
	OCO_ID			INT						NOT NULL FOREIGN KEY REFERENCES CG_OCORRENCIA(OCO_ID)
);

CREATE TABLE CG_VISITANTE(
	VIS_ID			INT IDENTITY(1,1)		NOT NULL PRIMARY KEY,
	VIS_NOME		VARCHAR(100)			NOT NULL,
	VIS_MOR			INT						NOT NULL FOREIGN KEY REFERENCES CG_MORADORES(MOR_ID)
);